---
title: "LMD_correction"
output: pdf_document
date: '2023-12-04'
---

score at $t$: $s^{(t)}=D_{KL}(p||p(t))=\sum_i-p_ilog\frac{w_{i}^tp}{p_i}$
pulse score at $t$: $D_{KL}(p||p^{\delta}(t))=\sum_i-p_ilog\frac{w_i^t\delta_i}{p_i}=\sum_i-p_ilog\frac{w_{i,i}^{t}}{p_{i}}$

# Load Data
```{r}
library("Seurat")
library("SeuratWrappers")
library("pheatmap")
library("ggplot2")
library("ggplotify")
source("LMD_function.R", echo = F)

tiss <- readRDS("/data/ruiqi/local_marker/dataset/tabular_muris/marrow_facs.rds")
DefaultAssay(tiss) <- "RNA"
n_dim = dim(tiss@reductions$pca@cell.embeddings)[2]
feature_space = as.matrix(tiss@reductions$pca@cell.embeddings[,1:n_dim])
visual_space = data.frame(tiss@reductions$tsne@cell.embeddings)
dat = as.matrix(tiss[[DefaultAssay(tiss)]]@data)
Gene_detected_count <- apply(dat > apply(dat,2,median),1,sum)
selected_genes = (Gene_detected_count >= 10) & (Gene_detected_count <= ncol(dat) * 0.5)
dat = dat[selected_genes,,drop = FALSE]
```

# Score curve plot
```{r}
W = Symmetric_KNN_graph(knn = 5, feature_space = feature_space)$graph
lmd_result = LMD(dat, feature_space)
lmd_result1 = LMD(dat, feature_space, score_correction = FALSE)

genes = c("Tlr11","Fcnb","Cd79a","4933425H06Rik","Uchl4","Dock11")
genes = c("Vpreb2","Cd200r3","Klra12","Cyp2ab1","Sycp2","Mup3")
genes = c("Abca13","Rag1","Mdga1","Trim47","Cd83","2610002D18Rik")

genes_label = rep(c("good","bad"),each = 3)
facet_label = rep(c(10,500,2000),2)
Visualize_score_pattern(lmd_result$score_profile, genes = genes, label_class = genes_label, facet_class = facet_label)

Visualize_score_pattern(lmd_result$score_profile[,1:16] - lmd_result$score_profile[,17:32], genes = genes, label_class = genes_label, facet_class = facet_label) + ylab("adjusted_score")
```
# plot w_ii with t
```{r}
w = do.call(rbind,lapply(P_ls,function(x){diag(x)}))
rownames(w) = names(P_ls)

pl = lapply(1:nrow(w),function(i){
  legend_break_label = seq(0, max(w[i,]), length.out = 2)
  if(max(legend_break_label)>1e-3){
      legend_break_label = signif(legend_break_label, digits = 2)
    }else{
      legend_break_label = formatC(legend_break_label, format = "e", digits = 0)
    }
  
  FeaturePlot_custom(value = w[i,]/max(w[i,]),coord = visual_space,title_name = paste0("T = ",rownames(w)[i])) + 
    scale_color_gradient(name = "Density",
                         low = "lightgrey", high = "blue",
                             limits = c(0,1),
                             breaks = seq(0, 1, length.out = 2),
                             labels = legend_break_label)
})
wrap_plots(pl,nrow = 2)
```
# Check diffusion status on graph
```{r}
gene = "Htr1b"
FeaturePlot_diffusion(coord = visual_space,init_state = rho[gene,],P_ls = P_ls,check_time = c(2^4,2^6,2^8),gene_name = gene)
```

# Delta function
```{r}
# Delta-function
lmd_result_delta = LMD(diag(ncol(dat)), feature_space)
Visualize_score_pattern(lmd_result_delta$score_profile, genes = "1", label_class = NULL, facet_class = NULL)

# Double-pulse
indices1 <- sample(ncol(dat), 50, replace = TRUE)
indices2 <- sample(ncol(dat), 50, replace = TRUE)
while(any(indices1 == indices2)) {
  indices2[indices1 == indices2] <- sample(n, sum(indices1 == indices2), replace = TRUE)
}
df = data.frame(t(apply(cbind(indices1,indices2),1,function(x){sort(x)}))) %>% distinct()
lmd_result_delta = LMD(
  t(apply(df,1,function(x){
  vec = numeric(ncol(dat))
  vec[x] = 1
  vec})), feature_space)
which.max(lmd_result_delta$cumulative_score)
Visualize_score_pattern(lmd_result_delta$score_profile, genes = c("35","22"), label_class = NULL, facet_class = NULL)

```



