// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastKLMatrix
NumericVector fastKLMatrix(NumericMatrix x, NumericMatrix y);
RcppExport SEXP _LocalizedMarkerDetector_fastKLMatrix(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastKLMatrix(x, y));
    return rcpp_result_gen;
END_RCPP
}
// fastKLVector
NumericVector fastKLVector(NumericMatrix x, NumericVector y);
RcppExport SEXP _LocalizedMarkerDetector_fastKLVector(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastKLVector(x, y));
    return rcpp_result_gen;
END_RCPP
}
// fastMatMult
arma::mat fastMatMult(arma::mat A, arma::mat B);
RcppExport SEXP _LocalizedMarkerDetector_fastMatMult(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(fastMatMult(A, B));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LocalizedMarkerDetector_fastKLMatrix", (DL_FUNC) &_LocalizedMarkerDetector_fastKLMatrix, 2},
    {"_LocalizedMarkerDetector_fastKLVector", (DL_FUNC) &_LocalizedMarkerDetector_fastKLVector, 2},
    {"_LocalizedMarkerDetector_fastMatMult", (DL_FUNC) &_LocalizedMarkerDetector_fastMatMult, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_LocalizedMarkerDetector(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
