# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastKLMatrix <- function(x, y) {
    .Call(`_LocalizedMarkerDetector_fastKLMatrix`, x, y)
}

fastKLVector <- function(x, y) {
    .Call(`_LocalizedMarkerDetector_fastKLVector`, x, y)
}

fastMatMult <- function(A, B) {
    .Call(`_LocalizedMarkerDetector_fastMatMult`, A, B)
}

